# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dpln_rcpp <- function(y, mu, sigma, log_p = FALSE) {
    .Call(`_poisLogn_dpln_rcpp`, y, mu, sigma, log_p)
}

